version: '3'
services:
    s1:
        build: .
        container_name: cb1
        ports: 
            - "3010:80"
            - "4000:88"
        # entrypoint: 
        #     - "/bin/bash"
        # command: 
        #     - "-it"
        # restart: always
    s2:
        build: .
        container_name: cb2
        depends_on: 
            - s1
        ports: 
            - "82:80"
            - "4100:81"
        # restart: always
        # entrypoint: 
        #     - "/bin/bash"
        # command: 
        #     - "-it"